##-------------------------
# SMS Analysis
##-------------------------

##Load Packages

require(tidyverse)
require(stringr)
require(gtools)
require(quanteda)
require(stopwords)
require(lubridate)


## Import CSVs that contain the SMS

setwd("~/Desktop/SMS Analysis")

tbl <-list.files(pattern = "*.csv")

sorted_files <- mixedsort(tbl) %>%  map_df(~read_csv(., skip = 1))


## Generate metrics on word counts

sms_metrics <- sorted_files %>% 
  transmute(Name, Content, Date) %>% 
  distinct(Content, .keep_all = TRUE) %>%
  filter(Name != "Generated by GilApps SMSShare 2") %>% 
  mutate(Word_Count = str_count(Content, "\\S+")) %>% 
  rename(Author = Name)

ggplot(sms_metrics, aes(x=Date, y=Word_Count)) + geom_smooth()

ggplot(sms_metrics, aes(x=Date, y=Word_Count, colour=Author)) + geom_jitter()

str_extract_all(sentences, boundary("word")) %>% 
  unlist() %>% 
  str_to_lower() %>% 
  tibble %>% 
  set_names("word") %>% 
  group_by(word) %>% 
  count(sort=TRUE) %>% 
  head(5)


## Build a corpus to assess readability

sms_corpus <- corpus(sms_metrics, text_field = "Content")

sms_corpus %>% 
  corpus_subset(Author == "Author2") %>% 
  dfm(remove = stopwords("english")) %>% 
  textplot_wordcloud()

Author_1_readability <- sms_corpus %>% 
  corpus_subset(Author == "Author1") %>% 
  textstat_readability(measure = "Flesch")

mean(Author_1_readability$Flesch)

Author_2_readability <- sms_corpus %>% 
  corpus_subset(Author == "Author2") %>% 
  textstat_readability(measure = "Flesch")

mean(Author_2_readability$Flesch)


## Find the time between messages

frequency_analysis <- sms_metrics %>%
  mutate(Time_Between = difftime(Date, lag(Date))) %>% 
  group_by(Author) %>%
  mutate(Abs_Time_Between = difftime(Date, lag(Date))) %>% 
  mutate(Author_Switch = if_else(Time_Between==Abs_Time_Between, FALSE, TRUE))

naive_time_approach <- frequency_analysis %>% # naive because overnights are included
  filter(Author_Switch == TRUE) %>% 
  group_by(Author) %>% 
  summarize(mean(Time_Between))

earliest_sms <- sms_metrics %>% 
  mutate(Hour = hour(sms_metrics$Date), Minute = minute(sms_metrics$Date), Second = second(sms_metrics$Date)) %>%
  arrange(Hour, Minute) %>% 
  select(Author, Date) %>%  
  head(1) 

latest_sms <- sms_metrics %>% 
  mutate(Hour = hour(sms_metrics$Date), Minute = minute(sms_metrics$Date), Second = second(sms_metrics$Date)) %>% 
  arrange(desc(Hour), desc(Minute)) %>% 
  select(Author, Date) %>%  
  head(1)